services:
  postgres:
    image: postgres:17
    container_name: huuthanhco-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: huuthanh_cms
    ports:
      - "5432:5432"
    volumes:
      - huuthanhco_postgres:/var/lib/postgresql/data

volumes:
  huuthanhco_postgres:
