CREATE DATABASE IF NOT EXISTS huuthanh_cms
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE huuthanh_cms;

CREATE TABLE IF NOT EXISTS news (
  id VARCHAR(120) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  published_date DATE NOT NULL,
  category VARCHAR(120) NOT NULL,
  category_en VARCHAR(120) NOT NULL,
  thumbnail TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  excerpt_en TEXT NOT NULL,
  content LONGTEXT NOT NULL,
  content_en LONGTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(120) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  year INT NOT NULL,
  category VARCHAR(120) NOT NULL,
  category_en VARCHAR(120) NOT NULL,
  image TEXT NOT NULL,
  description TEXT NOT NULL,
  description_en TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
  id VARCHAR(120) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  type VARCHAR(120) NOT NULL,
  type_en VARCHAR(120) NOT NULL,
  salary VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  description_en TEXT NOT NULL,
  requirements JSON NOT NULL,
  requirements_en JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
