CREATE TABLE IF NOT EXISTS news (
  id VARCHAR(120) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  published_date DATE NOT NULL,
  category VARCHAR(120) NOT NULL,
  category_en VARCHAR(120) NOT NULL,
  thumbnail TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  excerpt_en TEXT NOT NULL,
  content TEXT NOT NULL,
  content_en TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(120) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  year INT NOT NULL,
  category VARCHAR(120) NOT NULL,
  category_en VARCHAR(120) NOT NULL,
  image TEXT NOT NULL,
  description TEXT NOT NULL,
  description_en TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
  id VARCHAR(120) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  type VARCHAR(120) NOT NULL,
  type_en VARCHAR(120) NOT NULL,
  salary VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  description_en TEXT NOT NULL,
  requirements JSONB NOT NULL,
  requirements_en JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_news_published_date ON news (published_date DESC);
CREATE INDEX IF NOT EXISTS idx_projects_year ON projects (year DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_updated_at ON jobs (updated_at DESC);
